// Interface automatically generated by schemas-to-ts

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    productId?: string;
    Nome: string;
    Description?: string;
    Created: Date;
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  productId?: string;
  Nome: string;
  Description?: string;
  Created: Date;
  locale: string;
  localizations?: Product[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  productId?: string;
  Nome: string;
  Description?: string;
  Created: Date;
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  productId?: string;
  Nome: string;
  Description?: string;
  Created: Date;
  locale: string;
  localizations?: Product[];
}
